### ISSUE TITLE
Update documentation for resolutions

### ISSUE THREAD

**Issue by emilorol** [aashutoshrathi/word-wrap#4]
Thank you for taking over this project. 

I think it make sense to add to the documentation the instructions on how to use your project as `resolutions` for `yarn` or `overrides` for `npm`.

Something alone the lines of:

If you are using `yarn` and a dependency needs your package then add the following to your `package.json`:

```json
  "resolutions": {
    "**/word-wrap": "npm:@aashutoshrathi/word-wrap"
  },
```
If you are using `npm` and a dependency needs your package then add the following to your `package.json`:
```json
  "overrides": {
    "**/word-wrap": "npm:@aashutoshrathi/word-wrap"
  },

**Comment by wellwelwel** [comment]
@aashutoshrathi, are you interested in maintaining support for this project?
> I think I already know the answer 🙋🏻‍♂️

So, can we contribute to your repository?

---

I would like to say that this repository is currently used by [**Optionator**](https://github.com/gkz/optionator), a direct dependency of [**ESLint**](https://github.com/eslint/eslint).

**Comment by aashutoshrathi** [comment]
Yup! I can

**Comment by aifrak** [comment]
Regarding the `npm` solution, the code above does not work for me (node 18, npm 9). This worked for me:
```json
  "overrides": {
    "word-wrap": "@aashutoshrathi/word-wrap"
  },
```

**Comment by emilorol** [comment]
To add this should I update the [.verb.md](https://github.com/aashutoshrathi/word-wrap/blob/master/.verb.md) or the `README.md` file ?
